# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.3
loom_version=1.11.8

# Mod Properties
mod_version=1.0.1
maven_group=com.glamardor
archives_base_name=absolute-cinema-camera

# Dependencies
fabric_api_version=0.136.1+1.21.8
cloth_config_version=19.0.147
modmenu_version=15.0.2
voicechat_api_version=2.6.20
